[ADD] enum to manage keyboard inputs
TempoDev/Arcade-Toulouse pull request #33
Opened 2021-03-29 19:51 UTC by Jad31

2021-03-29 19:53 UTC, nasso requested changes

2021-03-29 19:53 UTC, nasso commented on src/keyboard.hpp
> +enum {
Il manque les include guards, le header Epitech, le namespace, et il vaut mieux utiliser `enum class` en C++.

2021-03-29 20:00 UTC, TempoDev commented
C'est beaucoup mieux ! 👍

2021-03-29 20:01 UTC, merged

2021-03-30 08:49 UTC, max-ndj commented
Il manque encore un truc, le enum class il lui faut un nom

2021-03-30 09:00 UTC, Jad31 commented
> Il manque encore un truc, le enum class il lui faut un nom

Yep, j'ai remarqué je l'ai rajouté après. Je push ça

2021-03-30 09:12 UTC, Jad31 commented
J'ai tout rajouter sur l'autre pull request #35 # # # #